name: API CI

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "apps/api/**"
      - "packages/**"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/api.ci.yml"
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "apps/api/**"
      - "packages/**"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/api-ci.yml"

jobs:
  linter_and_unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate
        working-directory: ./apps/api

      - name: Run linter
        run: npm run lint:api

      - name: Run unit tests
        run: npm run test:unit:api

  integration-tests:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/prescription_app
      JWT_ACCESS_SECRET: secreto
      JWT_ACCESS_TTL: 900s
      JWT_REFRESH_SECRET: secreto
      JWT_REFRESH_TTL: 7d

    services:
      postgre-e2e:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: prescription_app
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: .

      - name: Generate Prisma Client
        run: npx prisma generate
        working-directory: ./apps/api

      - name: Run migrations
        run: npm run migration:test:api

      - name: Run integration tests
        run: npm run test:int:api

  e2e-tests:
    runs-on: ubuntu-latest
    env:
      PORT: 3000
      FRONTEND_URL: http://localhost
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/prescription_app
      JWT_ACCESS_SECRET: secreto
      JWT_ACCESS_TTL: 900s
      JWT_REFRESH_SECRET: secreto
      JWT_REFRESH_TTL: 7d
      THROTTLE_GLOBAL_TTL: 60000
      THROTTLER_GLOBAL_LIMIT: 100
      THROTTLE_AUTH_TTL: 60000
      THROTTLER_AUTH_LIMIT: 5

    services:
      postgre-e2e:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: prescription_app
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: .

      - name: Generate Prisma Client
        run: npx prisma generate
        working-directory: ./apps/api

      - name: Run migrations
        run: npm run migration:test:api

      - name: Run e2e tests
        run: npm run test:e2e:api
